Change to count cause error for update to php 8.2
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given